EasyBook/HotelBook/Controllers/AdminController.cs
using HotelBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
namespace HotelBook.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult request()

        {
            HotelDBContext hotelDb = new HotelDBContext();
            List<Customer> range = hotelDb.Viewcustomer();
            return View(range);
        }
        public ActionResult setAccept(string email)
        {
            HotelDBContext hotelDb = new HotelDBContext();
            Debug.WriteLine(email);
            List<Customer> range = hotelDb.Viewcustomer();
            string h = email;
            hotelDb.set(h);
            hotelDb.sendMail(h);
            return View("~/Views/Admin/request.cshtml",range);
        }
        public void setReject(string email)
        {
            HotelDBContext hotelDb = new HotelDBContext();


            string h = email;
            hotelDb.setr(h);

        }


        public ActionResult user()

        {
            HotelDBContext hotelDb = new HotelDBContext();
            List<Customer> range2 = hotelDb.Viewuser();
            return View(range2);
        }
        public ActionResult logout()
        {
            return View("~/Views/Home/index.cshtml");
        }
        [HttpGet]
        public ActionResult upsetting()
        {
            HotelDBContext hotelDb = new HotelDBContext();
            Customer range = hotelDb.Viewsettings();
            return View(range);

        }
        [HttpPost]
        public ActionResult upsetting(Customer customer)
        {
            HotelDBContext hotelDb = new HotelDBContext();
            hotelDb.upseting(customer);
            return View();
        }

        public ActionResult post()

        {
            admin hotelDb = new admin();
            // List<DateTime> arr = hotelDb.GetPostData();
            //  List<DateTime> arr2 = hotelDb.GetAlbumData();
            // List<DateTime> arr3 = hotelDb.GetEventData();
            // var all = arr3.Concat(arr2).Concat(arr).ToList();
            /// List<DateTime> lok = all.Distinct().ToList();
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;




            /*  foreach (var item in viewModel.TheThirdTable)
              {
                  Debug.WriteLine(item);
                  viewModel.ThefourthTable= hotelDb.getImages(item.albumName);
              }
                  Debug.WriteLine("added");


         */
            return View(viewModel);
        }

        public ActionResult doPostReject(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doPostRejects(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }

        public ActionResult doPostDelete(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doPostDelete(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doPostAccept(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doPostAccept(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doEventDelete(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doEventDelete(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doEventRejects(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doEventRejects(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doEventAccept(int id)
        {
            admin hotelDb = new admin();

            hotelDb.doEventAccept(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;


            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doAlbumDelete(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doAlbumDelete(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doAlbumRejects(int id)
        {
            admin hotelDb = new admin();
            hotelDb.doAlbumRejects(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;



            return View("~/Views/Admin/post.cshtml", viewModel);
        }
        public ActionResult doAlbumAccept(int id)
        {
            admin hotelDb = new admin();

            hotelDb.doAlbumAccept(id);
            DateTime today = DateTime.Today;
            DateTime daye = today.AddDays(-14).Date;
            Debug.WriteLine(daye);
            MyViewModel viewModel = new MyViewModel();
            viewModel.TheSecondTable = hotelDb.getPostEvents(daye);
            viewModel.TheFirstTable = hotelDb.getPostPosts(daye);
            viewModel.TheThirdTable = hotelDb.getAlbumName(daye);
            viewModel.ThefourthTable = hotelDb.getImg(daye);
            viewModel.crntdate = DateTime.Today.Date;


            return View("~/Views/Admin/post.cshtml", viewModel);
        }

    }
}

EasyBook/HotelBook/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HotelBook.Models;
using System.Web.Mvc;
using System.IO;

namespace HotelBook.Controllers
{
    public class RentController : Controller
    {
        // GET: Rent
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Boarding(string searchstring)
        {
            HotelDB hotelDb = new HotelDB();

            
           
            String city = "Null";
            
            if (!String.IsNullOrEmpty(searchstring))
            {
                city = searchstring;
            }
            List<Boarding> range = hotelDb.viewBoarding(city);

            return View("~/Views/Rent/Boarding.cshtml", range);
        }

        [HttpGet]
        public ActionResult Boarding()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Settings()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Settings1(string searchstring)
        {
            String name = "Null";
            HotelDB hotelDb = new HotelDB();
            
            
            if (!String.IsNullOrEmpty(searchstring))
            {
                name = searchstring;
            }
            
            List<Boarding> range = hotelDb.viewAdd(name);

            return View("~/Views/Rent/Settings1.cshtml", range);
        }

        [HttpGet]
        public ActionResult Advertisement()
        {

            return View();
        }
        public ActionResult DeleteView(int id)
        {
            HotelDB hotelDb = new HotelDB();
            Boarding board=hotelDb.DeleteAddView(id);
            return View("~/Views/Rent/DeleteView.cshtml",board);
        }
        public ActionResult DeleteAdd(int id,Boarding b)
        {
            HotelDB hotelDb = new HotelDB();
            hotelDb.DeleteAdd(id,b);
            return View("~/Views/Rent/Settings.cshtml");
        }

        [HttpPost]
        public ActionResult advertisement(string searchstring, string searchstring1,string searchstring2, string searchstring3, string searchstring4, string searchstring5, string searchstring6, HttpPostedFileBase file)
        {
            var path= "";
            if (file!=null)
            {
                if (file.ContentLength > 0)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg")
                    {
                        path = Path.Combine(Server.MapPath("~/image/upload"),file.FileName);
                        file.SaveAs(path);
                        ViewBag.UploadSuccess = "true";
                    }
                }
            }
            HotelDB hotelDb = new HotelDB();


            String email = "Null";
            String name = "Null";
            String city = "Null";
            String telephone = "Null";
            String address = "Null";
            String password = "Null";
            String description = "Null";
            if (!String.IsNullOrEmpty(searchstring))
            {
                email = searchstring;
            }
            if (!String.IsNullOrEmpty(searchstring1))
            {
                name = searchstring1;
            }
            if (!String.IsNullOrEmpty(searchstring2))
            {
                address = searchstring2;
            }
            if (!String.IsNullOrEmpty(searchstring3))
            {
                city = searchstring3;
            }
            if (!String.IsNullOrEmpty(searchstring4))
            {
                telephone = searchstring4;
            }
            if (!String.IsNullOrEmpty(searchstring5))
            {
                description = searchstring5;
            }
            if (!String.IsNullOrEmpty(searchstring6))
            {
                password = searchstring6;
            }
            hotelDb.advertisement(email,name,address,city,telephone,description, password, file.FileName);

            return View();
        }
    }

}

EasyBook/HotelBook/Views/Shared/_Header.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title = EasyBook</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="@Url.Content("~/Styles/boostrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Styles/Site.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Script/modernizr-2.6.2.js")" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" language="javascript" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.min.js")"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.Jcrop.js")"></script>
    <script src="@Url.Content("~/Script/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Script/bootstrap.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Script/jquery.js")" language="javascript" type="text/javascript"></script>
    <script src="@Url.Content("~/Script/boostrap.js")" language="javascript" type="text/javascript"></script>

</head>
<body >
    <div class="col-md-12 navbar navbar-inverse navbar-fixed-top" style="height:50px;">
        <div class="container">
            
                
            
                <ul class="nav navbar-nav navbar-right" style="margin-right:10px;" >
                    @if (@Session["Email"] == null && @Session["user"] == null )
                    {
                    <li>@Html.ActionLink("LogIn", "Index", "Login")</li>
                    <li>@Html.ActionLink("SignUp", "Signup", "Login")</li>
                    }
                    else if (@Session["user"] != null)
                    {
                        <li><p class="navbar-brand" style="font-size:12px;">Logged In as @Session["user"]</p></li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "Login")</li>
                    }
                    else
                    {
                    <li><p class = "navbar-brand" style="font-size:12px;">Logged In as @Session["Email"]</p></li>
                    <li>@Html.ActionLink("Profile", "post", "profile", new { email = @Session["Email"].ToString() }, new { })</li>

                    <li>@Html.ActionLink("LogOut", "LogOut", "Login")</li>
                    }

                </ul>
                </div>
        </div>
    <div class="col-md-12 navbar-inverse navbar-top" style="height:100px;padding-top:5px;">
        <div  align="center">

            <p align="center" style="color:yellow"><span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   </p>
            @Html.ActionLink("EasyBook", "start", "Home", "", new { align = "center", style = "font-size:24px;color:white;" })

            <hr style="border:1px solid yellow" />

        </div>


    </div>
    <div style="background-color:white;">
      
    
        @RenderBody()

    </div>

<div class="col-md-12" style="color:white;">

    
    <footer>
        <p>&copy; @DateTime.Now.Year - EasyBook</p>
    </footer>
</div>




</body>
</html>

EasyBook/HotelBook/Views/Shared/_Header1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title = EasyBook</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="@Url.Content("~/Styles/boostrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Styles/Site.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Script/modernizr-2.6.2.js")" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" language="javascript" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.min.js")"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.Jcrop.js")"></script>
    <script src="@Url.Content("~/Script/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Script/bootstrap.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Script/jquery.js")" language="javascript" type="text/javascript"></script>
    <script src="@Url.Content("~/Script/boostrap.js")" language="javascript" type="text/javascript"></script>

</head>
<body >
    <div class="col-md-12 navbar navbar-inverse navbar-fixed-top" style="height:50px;">
        <div class="container">
            
                
            
                <ul class="nav navbar-nav navbar-right" style="margin-right:10px;" >
                    @if (@Session["Email"] == null)
                    {
                    <li>@Html.ActionLink("Advertisement", "Advertisement", "Rent")</li>
                    <li>@Html.ActionLink("Settings", "Settings", "Rent")</li>
					<li>@Html.ActionLink("Search", "Index", "Rent")</li>
                    }else{

                    <li><p class = "navbar-brand" style="font-size:12px;">Logged In as @Session["Email"]</p></li>
                    <li>@Html.ActionLink("LogOut", "LogOut", "Login")</li>
                    }

                </ul>
                </div>
        </div>
    <div class="col-md-12 navbar-inverse navbar-top" style="height:100px;padding-top:5px;">
        <div  align="center">

            <p align="center" style="color:yellow"><span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   </p>
            @Html.ActionLink("EasyBook", "start", "Home", "", new { align = "center", style = "font-size:24px;color:white;" })

            <hr style="border:1px solid yellow" />

        </div>


    </div>
    <div class="col-md-12 " style="padding-left:20px;padding-right:20px;background-color:white;">
      
   
        @RenderBody()
    @RenderSection("scripts", required: false)

        </div>

<div class="col-md-12" style="color:white;">

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - EasyBook</p>
    </footer>
</div>




</body>
</html>

EasyBook/HotelBook/Views/Shared/_Header2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title = EasyBook</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="@Url.Content("~/Styles/boostrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Styles/Site.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Script/modernizr-2.6.2.js")" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" language="javascript" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" language="javascript" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.min.js")"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Script/jquery.Jcrop.js")"></script>


</head>
<body>
    <div class="col-md-12 navbar navbar-inverse navbar-fixed-top" style="height:50px;">
        <div class="container">



            <ul class="nav navbar-nav navbar-right" style="margin-right:10px;">
                @if (@Session["Email"] == null)
                {
                    <li>@Html.ActionLink("Settings", "upsetting", "Admin")</li>
                    <li>@Html.ActionLink("Logout", "logout", "Admin")</li>

                }
                else
                {

                    <li><p class="navbar-brand" style="font-size:12px;">Logged In as @Session["Email"]</p></li>
                    <li>@Html.ActionLink("LogOut", "LogOut", "Login")</li>
                }

            </ul>
        </div>
    </div>
    <div class="col-md-12 navbar-inverse navbar-top" style="height:100px;padding-top:5px;">
        <div align="center">

            <p align="center" style="color:yellow"><span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   <span class="glyphicon glyphicon-star"></span>   </p>
            @Html.ActionLink("EasyBook", "start", "Home", "", new { align = "center", style = "font-size:24px;color:white;" })

            <hr style="border:1px solid yellow" />

        </div>


    </div>
    <div class="col-lg-12 " style="padding-left:20px;padding-right:20px;">

        <div class="col-lg-12 body-cont" style="">
            @RenderBody()
            @RenderSection("scripts", required: false)
        </div>
    </div>

    <div style="color:white;">

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - EasyBook</p>
        </footer>
    </div>
    <script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Script/jquery.js")" language="javascript" type="text/javascript"></script>
    <script src="@Url.Content("~/Script/boostrap.js")" language="javascript" type="text/javascript"></script>



</body>
</html>